create Node.js Hello World Microservice example
mia-platform-marketplace/Node.js-Hello-World-Microservice-Example pull request #1
Opened 2019-11-20 16:12 UTC by Luca-Ferrera

2019-11-21 10:44 UTC, fredmaggiowski commented
@Luca-Ferrera there are conflicts, please resolve them.

I think that the README title shall be interpolated so it should be a simple fix.

2019-11-21 11:53 UTC, fredmaggiowski requested changes

2019-11-21 11:53 UTC, fredmaggiowski commented on default.env
> +USERID_HEADER_KEY=miauserid
remove `mia` from these env variables.

2019-11-21 11:53 UTC, fredmaggiowski commented on docs/index.md
> +# %CUSTOM_PLUGIN_SERVICE_NAME%
This file is useless, remove it

2019-11-25 15:36 UTC, davidebianchi requested changes

2019-11-25 15:36 UTC, davidebianchi commented on CHANGELOG.md
> +- Inital version
```suggestion
- Initial version
```

2019-11-25 15:36 UTC, davidebianchi commented on scripts/update-version.sh
> +#!/usr/bin/env sh
We should add the copyright lines also in this file

2019-11-25 15:52 UTC, davidebianchi approved these changes

2019-11-25 16:19 UTC, fredmaggiowski approved these changes

2019-11-25 16:20 UTC, merged